// ===== 商品假数据 =====
// 使用 Unsplash 真实图片（包包/时尚相关）
const PRODUCTS = [
  {
    id: 1,
    name: "高级真皮水桶包",
    category: "水桶包",
    desc: "意大利进口头层牛皮，经典圆筒形款式，大容量设计",
    price: 1299,
    oldPrice: 1599,
    discount: "4折起",
    rating: 4.8,
    ratingScore: "4.8",
    reviews: 234,
    sold: 1342,
    badge: "hot",
    badgeText: "HOT",
    images: [
      "image/水桶包1.jpg",
      "image/水桶包2.jpg",
      "image/水桶包3.jpg",
      "image/水桶包1.jpg",
    ],
    colors: ["#1a1a1a", "#8B4513", "#C0C0C0", "#8B0000"],
    sizes: ["小号 (18*10*22cm)", "中号 (22*12*26cm)", "大号 (26*14*30cm)"],
    highlights: [
      "采用意大利进口头层牛皮制作，质感细腻，手感柔滑丝滑",
      "经典圆筒形设计，时尚百搭，适合各种场合携带",
      "大容量主仓设计，方便收纳各种日常物品",
      "内置多功能口袋分区，化妆品、手机、钱包各就各位",
      "可调节肩带，一包多用，手提肩挎均可",
    ],
    params: [
      { key: "品牌", val: "LUXE BAG" },
      { key: "材质", val: "头层牛皮" },
      { key: "产地", val: "意大利" },
      { key: "开合方式", val: "磁扣" },
      { key: "适用场景", val: "日常/旅行" },
      { key: "风格", val: "时尚简约" },
    ],
  },
  {
    id: 2,
    name: "复古真皮手提包",
    category: "手提包",
    desc: "大容量设计，经典复古风格感，多用百搭设计",
    price: 1599,
    oldPrice: 1899,
    discount: "85折",
    rating: 4.6,
    ratingScore: "4.6",
    reviews: 512,
    sold: 445,
    badge: null,
    images: [
      "image/手提包1.jpg",
      "image/手提包2.jpg",
      "image/手提包1.jpg",
    ],
    colors: ["#8B4513", "#D2691E", "#1a1a1a"],
    sizes: ["标准款 (30*12*24cm)", "大号 (35*14*28cm)"],
    highlights: [
      "大容量主仓，日常通勤、出行必备",
      "复古金属五金配件，品质感十足",
      "多隔层设计，分区收纳，整洁有序",
      "优质头层牛皮，耐用且越用越有韵味",
    ],
    params: [
      { key: "品牌", val: "LUXE BAG" },
      { key: "材质", val: "头层牛皮" },
      { key: "开合方式", val: "拉链+磁扣" },
      { key: "风格", val: "复古" },
      { key: "适用场景", val: "通勤/日常" },
      { key: "颜色数", val: "3色可选" },
    ],
  },
  {
    id: 3,
    name: "轻奢时尚手夹包",
    category: "手袋",
    desc: "高定制作金属链条，精细手工刺绣，清凉十足",
    price: 2199,
    oldPrice: 2799,
    discount: "79折",
    rating: 4.9,
    ratingScore: "4.9",
    reviews: 134,
    sold: 336,
    badge: "sale",
    badgeText: "SALE",
    images: [
      "image/手提包1.jpg",
      "image/手提包2.jpg",
    ],
    colors: ["#FFD700", "#C0C0C0", "#FF69B4", "#1a1a1a"],
    sizes: ["均码 (22*5*14cm)"],
    highlights: [
      "高定制作，金属链条精工细作",
      "手工刺绣图案，独一无二的艺术感",
      "轻奢风格，宴会、晚宴场合首选",
      "内置卡位和镜子，实用精致两不误",
    ],
    params: [
      { key: "品牌", val: "LUXE BAG" },
      { key: "材质", val: "进口小牛皮" },
      { key: "五金", val: "镀金五金" },
      { key: "风格", val: "轻奢/宴会" },
      { key: "适用场景", val: "宴会/派对" },
    ],
  },
  {
    id: 4,
    name: "潮流腰包",
    category: "腰包",
    desc: "时尚百搭，多功能口袋，轻便出行必备",
    price: 399,
    oldPrice: 499,
    discount: "8折",
    rating: 4.5,
    ratingScore: "4.5",
    reviews: 89,
    sold: 512,
    badge: null,
    images: [
      "image/路易威登-all-in-bb-手袋.png",
      "image/水桶包2.jpg",
    ],
    colors: ["#1a1a1a", "#808080", "#228B22"],
    sizes: ["均码"],
    highlights: [
      "多口袋设计，分类收纳，日常出行更便捷",
      "防泼水面料，不惧突发天气",
      "可拆卸背带，既可腰挎也可斜挎",
      "时尚百搭，街头风格首选",
    ],
    params: [
      { key: "品牌", val: "LUXE BAG" },
      { key: "材质", val: "尼龙+PU" },
      { key: "风格", val: "街头/运动" },
      { key: "适用场景", val: "户外/日常" },
    ],
  },
  {
    id: 5,
    name: "商务休闲双肩包",
    category: "双肩包",
    desc: "15寸笔记本电脑可放，多格设计，减压背带",
    price: 899,
    oldPrice: 1199,
    discount: "75折",
    rating: 4.7,
    ratingScore: "4.7",
    reviews: 342,
    sold: 1034,
    badge: null,
    images: [
      "image/双肩包1.jpg",
      "image/水桶包1.jpg",
    ],
    colors: ["#1a1a1a", "#003366", "#808080"],
    sizes: ["标准款 (30*15*45cm)"],
    highlights: [
      "专设15英寸笔记本电脑隔层，保护贴心",
      "人体工学设计背带，长途背负也不累",
      "多功能分区，商务出行、日常通勤均可",
      "优质防水面料，雨天也不担心",
    ],
    params: [
      { key: "品牌", val: "LUXE BAG" },
      { key: "材质", val: "头层牛皮" },
      { key: "容量", val: "约30L" },
      { key: "风格", val: "商务/休闲" },
      { key: "适用场景", val: "商务/出行" },
    ],
  },
  {
    id: 6,
    name: "复古斜挎包",
    category: "斜挎包",
    desc: "头层皮，手工缝制，复古风浓厚，文艺青年必备",
    price: 799,
    oldPrice: 1099,
    discount: "73折",
    rating: 4.6,
    ratingScore: "4.6",
    reviews: 78,
    sold: 286,
    badge: "new",
    badgeText: "NEW",
    images: [
      "image/斜挎包1.jpg",
      "image/路易威登-all-in-bb-手袋.png",
    ],
    colors: ["#8B4513", "#1a1a1a", "#D2B48C"],
    sizes: ["小号 (20*8*16cm)", "大号 (26*10*20cm)"],
    highlights: [
      "复古植鞣革，随使用增添独特包浆感",
      "全手工缝制，细节工艺精湛",
      "磁扣+插销双重保险，安全不丢物",
      "可调节肩带，适合不同身材",
    ],
    params: [
      { key: "品牌", val: "LUXE BAG" },
      { key: "材质", val: "植鞣革" },
      { key: "工艺", val: "全手工缝制" },
      { key: "风格", val: "复古/文艺" },
    ],
  },
  {
    id: 7,
    name: "时尚晚宴手提包",
    category: "手袋",
    desc: "水晶镶嵌，锁扣设计，奢华晚宴必备单品",
    price: 1299,
    oldPrice: 1599,
    discount: "81折",
    rating: 4.8,
    ratingScore: "4.8",
    reviews: 56,
    sold: 342,
    badge: "hot",
    badgeText: "HOT",
    images: [
      "image/路易威登-all-in-bb-手袋.png",
      "image/手提包1.jpg",
    ],
    colors: ["#FFD700", "#C0C0C0", "#FF1493"],
    sizes: ["均码 (20*6*12cm)"],
    highlights: [
      "精致水晶镶嵌，华丽夺目",
      "经典锁扣设计，优雅不失安全",
      "配有可拆卸细链，可手提可肩挎",
    ],
    params: [
      { key: "品牌", val: "LUXE BAG" },
      { key: "材质", val: "进口漆皮" },
      { key: "五金", val: "镀金水晶" },
      { key: "风格", val: "奢华/晚宴" },
    ],
  },
  {
    id: 8,
    name: "迷你可爱手提包",
    category: "手提包",
    desc: "小巧玲珑，多色可选，甜美可爱，百搭减龄",
    price: 599,
    oldPrice: 799,
    discount: "75折",
    rating: 4.5,
    ratingScore: "4.5",
    reviews: 210,
    sold: 645,
    badge: null,
    images: [
      "image/手提包1.jpg",
      "image/水桶包3.jpg",
    ],
    colors: ["#FFB6C1", "#E6E6FA", "#FFDAB9", "#98FB98"],
    sizes: ["小号 (16*8*12cm)", "中号 (20*10*16cm)"],
    highlights: [
      "小巧可爱，日常约会、购物首选",
      "多色可选，满足不同穿搭需求",
      "优质PU皮，轻便且耐用",
      "内有手机夹层，方便取用",
    ],
    params: [
      { key: "品牌", val: "LUXE BAG" },
      { key: "材质", val: "优质PU皮" },
      { key: "风格", val: "甜美/减龄" },
      { key: "适用场景", val: "约会/购物" },
    ],
  },
  {
    id: 9,
    name: "商务优雅公文包",
    category: "手提包",
    desc: "专业简约设计，商务出行必备，大容量隔层",
    price: 1599,
    oldPrice: 1999,
    discount: "8折",
    rating: 4.7,
    ratingScore: "4.7",
    reviews: 156,
    sold: 523,
    badge: "hot",
    badgeText: "HOT",
    images: [
      "image/手提包1.jpg",
      "image/手提包2.jpg",
    ],
    colors: ["#1a1a1a", "#8B4513", "#003366"],
    sizes: ["标准款 (40*30*12cm)"],
    highlights: [
      "专业设计感十足，商务场合首选",
      "大容量主仓+多隔层，分类有序",
      "高级头层牛皮，质感上乘",
      "可放置15寸笔记本电脑",
    ],
    params: [
      { key: "品牌", val: "LUXE BAG" },
      { key: "材质", val: "头层牛皮" },
      { key: "风格", val: "商务/专业" },
      { key: "适用场景", val: "商务出行" },
    ],
  },
  {
    id: 10,
    name: "运动休闲腋下包",
    category: "腰包",
    desc: "新款腋下包，百搭显气质，轻奢风格",
    price: 699,
    oldPrice: 899,
    discount: "78折",
    rating: 4.6,
    ratingScore: "4.6",
    reviews: 298,
    sold: 789,
    badge: null,
    images: [
      "image/水桶包2.jpg",
      "image/斜挎包1.jpg",
    ],
    colors: ["#1a1a1a", "#C0C0C0", "#FF8C00"],
    sizes: ["均码"],
    highlights: [
      "时尚腋下包设计，简约百搭",
      "软皮材质，舒适贴身",
      "多口袋设计，实用方便",
      "可单肩斜挎，颇显气质",
    ],
    params: [
      { key: "品牌", val: "LUXE BAG" },
      { key: "材质", val: "头层牛皮" },
      { key: "风格", val: "时尚/休闲" },
      { key: "适用场景", val: "日常/约会" },
    ],
  },
  {
    id: 11,
    name: "古董金色手夹包",
    category: "手袋",
    desc: "复古古董风格，金属链条，高级感十足",
    price: 1899,
    oldPrice: 2399,
    discount: "79折",
    rating: 4.8,
    ratingScore: "4.8",
    reviews: 89,
    sold: 267,
    badge: "sale",
    badgeText: "SALE",
    images: [
      "image/手提包2.jpg",
      "image/水桶包1.jpg",
    ],
    colors: ["#FFD700", "#C0C0C0", "#8B4513"],
    sizes: ["均码 (25*4*15cm)"],
    highlights: [
      "复古造型，彰显个性品味",
      "金色金属链条，质感十足",
      "高级进口小牛皮，柔软舒适",
      "内置卡位和镜子，实用精致",
    ],
    params: [
      { key: "品牌", val: "LUXE BAG" },
      { key: "材质", val: "进口小牛皮" },
      { key: "五金", val: "镀金五金" },
      { key: "风格", val: "复古/古董" },
    ],
  },
  {
    id: 12,
    name: "柔软羊皮大容量包",
    category: "手提包",
    desc: "柔软舒适，大容量实用，日常通勤首选",
    price: 1299,
    oldPrice: 1699,
    discount: "76折",
    rating: 4.6,
    ratingScore: "4.6",
    reviews: 423,
    sold: 1156,
    badge: null,
    images: [
      "image/手提包1.jpg",
      "image/手提包2.jpg",
    ],
    colors: ["#8B4513", "#1a1a1a", "#D2B48C", "#8B0000"],
    sizes: ["小号 (28*14*20cm)", "大号 (34*18*26cm)"],
    highlights: [
      "柔软羊皮，手感顺滑舒适",
      "大容量主仓，日常用品轻松装纳",
      "多隔层设计，分类整洁有序",
      "通勤必备，百搭百搭",
    ],
    params: [
      { key: "品牌", val: "LUXE BAG" },
      { key: "材质", val: "羊皮" },
      { key: "风格", val: "柔和/通勤" },
      { key: "适用场景", val: "通勤/日常" },
    ],
  },
  {
    id: 13,
    name: "防水户外登山包",
    category: "双肩包",
    desc: "防水防尘，户外运动专用，耐磨耐用",
    price: 799,
    oldPrice: 999,
    discount: "8折",
    rating: 4.5,
    ratingScore: "4.5",
    reviews: 267,
    sold: 834,
    badge: "new",
    badgeText: "NEW",
    images: [
      "image/双肩包1.jpg",
      "image/水桶包3.jpg",
    ],
    colors: ["#1a1a1a", "#228B22", "#FF6347"],
    sizes: ["标准款 (35*20*50cm)"],
    highlights: [
      "防水防尘面料，恶劣天气不惧怕",
      "多隔层+专属工具搭扣，装纳有序",
      "人体工学背带，长途舒适无压力",
      "户外运动、登山旅行必备",
    ],
    params: [
      { key: "品牌", val: "LUXE BAG" },
      { key: "材质", val: "防水尼龙" },
      { key: "容量", val: "50L" },
      { key: "风格", val: "户外/运动" },
    ],
  },
  {
    id: 14,
    name: "简约黑色相机包",
    category: "斜挎包",
    desc: "专业相机包设计，防护性强，旅行拍摄首选",
    price: 899,
    oldPrice: 1199,
    discount: "75折",
    rating: 4.7,
    ratingScore: "4.7",
    reviews: 178,
    sold: 445,
    badge: null,
    images: [
      "image/斜挎包1.jpg",
      "image/水桶包1.jpg",
    ],
    colors: ["#1a1a1a", "#808080", "#00008B"],
    sizes: ["标准款 (32*24*12cm)"],
    highlights: [
      "专业相机包设计，防护隔层多",
      "防水面料，保护贵重相机设备",
      "可调节内隔，满足不同相机组合",
      "斜挎舒适，专业摄影师首选",
    ],
    params: [
      { key: "品牌", val: "LUXE BAG" },
      { key: "材质", val: "防水尼龙" },
      { key: "风格", val: "专业/简约" },
      { key: "适用场景", val: "摄影/旅行" },
    ],
  },
  {
    id: 15,
    name: "软糖配色迷你包",
    category: "手袋",
    desc: "卡通可爱配色，少女心爆棚，小清新风格",
    price: 459,
    oldPrice: 599,
    discount: "77折",
    rating: 4.4,
    ratingScore: "4.4",
    reviews: 534,
    sold: 1204,
    badge: null,
    images: [
      "image/手提包1.jpg",
      "image/水桶包2.jpg",
    ],
    colors: ["#FFB6C1", "#B0E0E6", "#FFE4B5", "#DDA0DD"],
    sizes: ["均码 (18*12*8cm)"],
    highlights: [
      "可爱软糖配色，少女心满满",
      "迷你身材，可爱百搭",
      "方便随身携带，约会购物必备",
      "柔软PU皮，手感舒适",
    ],
    params: [
      { key: "品牌", val: "LUXE BAG" },
      { key: "材质", val: "优质PU皮" },
      { key: "风格", val: "可爱/小清新" },
      { key: "适用场景", val: "日常/约会" },
    ],
  },
  {
    id: 16,
    name: "精致珍珠白手包",
    category: "手袋",
    desc: "优雅珍珠白，高级质感，气质女人必备",
    price: 1399,
    oldPrice: 1799,
    discount: "78折",
    rating: 4.8,
    ratingScore: "4.8",
    reviews: 312,
    sold: 678,
    badge: "hot",
    badgeText: "HOT",
    images: [
      "image/手提包2.jpg",
      "image/手提包1.jpg",
    ],
    colors: ["#F5F5DC", "#FFE4E1", "#F0F8FF"],
    sizes: ["均码 (24*8*16cm)"],
    highlights: [
      "珍珠白配色，优雅气质十足",
      "高级质感小牛皮，柔软舒适",
      "精致金属五金，彰显品味",
      "气质女人必备款，宴会通勤两相宜",
    ],
    params: [
      { key: "品牌", val: "LUXE BAG" },
      { key: "材质", val: "进口小牛皮" },
      { key: "五金", val: "镀金五金" },
      { key: "风格", val: "优雅/气质" },
    ],
  },
];
